# infra/helm/charts/redis/templates/service.yaml
{{- /*
Creates:
  1) Headless Service (optional) used by the StatefulSet for stable DNS.
  2) Client Service used by applications to talk to Redis.

Relies on values defined in values.yaml:
  service:
    type: ClusterIP|LoadBalancer|NodePort
    port: 6379
    annotations: {}
    labels: {}
    sessionAffinity: None
    sessionAffinityConfig: {}
    externalTrafficPolicy: Local|Cluster (LB/NodePort)
    loadBalancerClass: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort: null

  headlessService:
    enabled: true
    annotations: {}
    labels: {}
    publishNotReadyAddresses: true

  metrics:
    enabled: true
    port: 9121
    service:
      enabled: true
      portName: metrics
*/ -}}

{{- /* ------------------------- Headless Service ------------------------- */ -}}
{{- if .Values.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.headlessName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cache
    helm.sh/chart: {{ include "redis.chart" . }}
    {{- with .Values.headlessService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.headlessService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: {{ default true .Values.headlessService.publishNotReadyAddresses }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
    {{- if and .Values.metrics.enabled .Values.metrics.service.enabled }}
    - name: {{ default "metrics" .Values.metrics.service.portName }}
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cache
---
{{- end }}

{{- /* --------------------------- Client Service -------------------------- */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cache
    helm.sh/chart: {{ include "redis.chart" . }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass | quote }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  sessionAffinity: {{ default "None" .Values.service.sessionAffinity }}
  {{- with .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- if and .Values.metrics.enabled .Values.metrics.service.enabled }}
    - name: {{ default "metrics" .Values.metrics.service.portName }}
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cache