# infra/helm/charts/minio/templates/secret.yaml
#
# Production-grade Secret for MinIO credentials (and optional extras like
# console admin, OIDC client secret, and SSE master key).
#
# Notes:
# - If you already manage secrets out-of-band (e.g., External Secrets), set
#   `.Values.secrets.existingSecret` and this template will not render.
# - Root user/password are required inputs unless `existingSecret` is set.
# - Keys are referenced by the Deployment:
#     MINIO_ROOT_USER        <- key: rootUser
#     MINIO_ROOT_PASSWORD    <- key: rootPassword
#     CONSOLE_ACCESS_KEY     <- key: consoleUser        (optional)
#     CONSOLE_SECRET_KEY     <- key: consolePassword    (optional)
#     MINIO_IDENTITY_OPENID_CLIENT_SECRET <- key: oidcClientSecret (optional)
#     MINIO_SSE_MASTER_KEY   <- key: sseMasterKey       (optional)
#
{{- if and .Values.secrets.enabled (not .Values.secrets.existingSecret) }}
{{- $name := default (printf "%s-minio" .Release.Name) .Values.nameOverride -}}
{{- $secretName := default (printf "%s-credentials" $name) .Values.secrets.name -}}
{{- $rootUser := required "values.secrets.rootUser is required when creating the Secret" .Values.secrets.rootUser -}}
{{- $rootPassword := required "values.secrets.rootPassword is required when creating the Secret" .Values.secrets.rootPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: bowdoin-marketplace
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- with .Values.secrets.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    kubernetes.io/description: "Credentials and secrets for MinIO (S3 API and optional Console)."
    {{- with .Values.secrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  # Required: server superuser credentials
  rootUser: {{ $rootUser | quote }}
  rootPassword: {{ $rootPassword | quote }}

  # Optional: MinIO Console built-in admin (if you don’t use OIDC for console)
  {{- with .Values.secrets.consoleUser }}
  consoleUser: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.consolePassword }}
  consolePassword: {{ . | quote }}
  {{- end }}

  # Optional: OIDC client secret if using MinIO as an OIDC client
  {{- with .Values.secrets.oidcClientSecret }}
  oidcClientSecret: {{ . | quote }}
  {{- end }}

  # Optional: SSE master key (use with care; prefer KMS if available)
  # Format commonly used by MINIO_SSE_MASTER_KEY is "key-id:hexkey"
  {{- with .Values.secrets.sseMasterKey }}
  sseMasterKey: {{ . | quote }}
  {{- end }}

  # Optional: any additional key/value pairs you want to mount as env
  {{- with .Values.secrets.extra }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}