# infra/helm/charts/app/templates/configmap.yaml
# Non-secret runtime configuration for the web app. This ConfigMap is intended
# to be mounted as envFrom (key-value pairs) and/or as files for structured
# config (YAML/JSON). Keep secrets in a Secret template.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default (printf "%s-config" .Chart.Name) .Values.app.configMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/part-of: bowdoin-marketplace
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    metrics.exposed: {{ ternary "true" "false" (default true .Values.monitoring.enabled) | quote }}
  annotations:
    # Bump this if you need to force a rollout from config-only changes
    bowdoin.io/config-version: {{ default "v1" .Values.app.configVersion | quote }}
data:
  # ---- Flat env-style configuration (safe, non-secret) ----
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  TZ: {{ .Values.app.timezone | default "UTC" | quote }}

  # Public runtime flags (safe to expose to the browser). Prefer NEXT_PUBLIC_*.
  NEXT_PUBLIC_ENV: {{ .Values.env | default "production" | quote }}
  NEXT_PUBLIC_APP_ORIGIN: {{ .Values.public.appOrigin | default (printf "https://%s" (default "app.example.com" .Values.ingress.host)) | quote }}
  NEXT_PUBLIC_API_BASE_URL: {{ .Values.public.apiBaseUrl | default "/api" | quote }}

  # Observability (non-secret endpoints/flags)
  LOG_LEVEL: {{ .Values.logging.level | default "info" | quote }}
  OTEL_SERVICE_NAME: {{ .Values.observability.serviceName | default .Chart.Name | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.observability.otlp.endpoint | default "http://otel-collector.observability.svc:4318" | quote }}
  OTEL_EXPORTER_OTLP_PROTOCOL: {{ .Values.observability.otlp.protocol | default "http/protobuf" | quote }}
  OTEL_TRACES_SAMPLER: {{ .Values.observability.traces.sampler | default "parentbased_traceidratio" | quote }}
  OTEL_TRACES_SAMPLER_ARG: {{ .Values.observability.traces.ratio | default "0.05" | quote }}

  # API surface / docs
  OPENAPI_URL: {{ .Values.openapi.url | default "/api/openapi" | quote }}

  # Rate limiting (non-secret policy)
  RATE_LIMIT_WINDOW_SECONDS: {{ .Values.rateLimit.windowSeconds | default 60 | quote }}
  RATE_LIMIT_MAX_REQUESTS: {{ .Values.rateLimit.maxRequests | default 120 | quote }}

  # Safe security-related toggles (no secrets)
  ENABLE_TRUST_PROXY: {{ ternary "true" "false" (default true .Values.security.enableTrustProxy) | quote }}
  ENABLE_CSRF_PROTECTION: {{ ternary "true" "false" (default true .Values.security.enableCsrf) | quote }}

  # ---- Structured config that can be mounted as files ----
  # Public security headers (the actual header values are non-secret)
  security-headers.yaml: |-
    {{- toYaml (default dict .Values.security.headers) | nindent 4 }}

  # Content-Security-Policy string (generated by app at runtime if empty)
  csp.txt: |-
    {{- default "" .Values.security.csp | nindent 4 }}

  # Feature flags (non-secret)
  flags.json: |-
    {{- toJson (default dict .Values.flags) | nindent 4 }}

  # App config (non-secret), e.g., pagination defaults, upload constraints, etc.
  app.yaml: |-
    {{- toYaml (default dict .Values.app.config) | nindent 4 }}

  # Public endpoints for third-party services (non-secret)
  endpoints.yaml: |-
    {{- toYaml (default dict .Values.endpoints) | nindent 4 }}