name: Monorepo CI

on:
  push:
    branches: [ main, develop, "release/*" ]
    paths-ignore:
      - "infra/**"
      - ".github/workflows/infra-deploy.yml"
      - "**/*.md"
      - "docs/**"
      - "ADRs/**"
      - ".changeset/**"
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "infra/**"
      - ".github/workflows/infra-deploy.yml"
      - "**/*.md"
      - "docs/**"
      - "ADRs/**"
      - ".changeset/**"
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

env:
  NODE_VERSION: "20.x"
  PNPM_VERSION: "10.17.1"
  NEXT_TELEMETRY_DISABLED: "1"
  CI: "1"

jobs:
  # -----------------------
  # Lint
  # -----------------------
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install pnpm FIRST so it's on PATH
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      # Then Node (no cache: pnpm here)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Show versions
        run: |
          node -v
          pnpm -v

      - name: Compute pnpm store path
        id: pnpm-store
        run: echo "STORE_PATH=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: PNPM network tuning
        run: |
          pnpm config set fetch-retries 5
          pnpm config set fetch-retry-factor 3
          pnpm config set fetch-retry-maxtimeout 60000
          pnpm config set fetch-retry-mintimeout 5000

      - name: Install deps (retry; frozen)
        run: |
          set -euo pipefail
          for n in 1 2 3; do
            pnpm install --frozen-lockfile && break || {
              echo "pnpm install failed (attempt $n). Retrying in 10s..."
              sleep 10
            }
          done

      - name: Prettier (check)
        run: pnpm -w exec prettier --check . || echo "Prettier not configured"

      - name: ESLint
        run: pnpm -w exec eslint . --ext .ts,.tsx,.mts,.cts || echo "ESLint not configured"

      - name: Upload pnpm logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-logs-lint
          path: |
            **/pnpm-debug.log
            pnpm-debug.log
          if-no-files-found: ignore
          retention-days: 7

  # -----------------------
  # Typecheck
  # -----------------------
  typecheck:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Compute pnpm store path
        id: pnpm-store
        run: echo "STORE_PATH=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install deps (resilient)
        run: |
          set -euo pipefail

          echo "::group::pnpm env & registry"
          pnpm -v
          node -v
          pnpm config list || true
          pnpm config get registry || true
          echo "lockfile sha256: $(sha256sum pnpm-lock.yaml | awk '{print $1}')" || true
          echo "::endgroup::"

          n=0
          until [ $n -ge 3 ]; do
            if pnpm install --frozen-lockfile; then
              OK=1; break
            fi
            n=$((n+1))
            echo "pnpm install --frozen-lockfile failed (attempt $n). Retrying in 10s..."
            sleep 10
          done

          if [ "${OK:-0}" != "1" ]; then
            echo "::warning::Frozen install failed after 3 attempts; checking for outdated lockfile…"
            if grep -E "ERR_PNPM_OUTDATED_LOCKFILE|Lockfile is up to date, but" -i pnpm-debug.log >/dev/null 2>&1; then
              echo "::notice::Detected lockfile drift; attempting non-frozen install (CI fallback)."
              pnpm install --no-frozen-lockfile
            else
              echo "::error::pnpm install failed; see pnpm-debug.log"
              exit 1
            fi
          fi

      - name: TypeScript - build mode
        run: pnpm -w exec tsc -b

      - name: Upload pnpm logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-logs-typecheck
          path: |
            **/pnpm-debug.log
            pnpm-debug.log
          if-no-files-found: ignore
          retention-days: 7

  # -----------------------
  # Build (workspace)
  # -----------------------
  build:
    runs-on: ubuntu-latest
    needs: [typecheck]
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Compute pnpm store path
        id: pnpm-store
        run: echo "STORE_PATH=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install deps (resilient)
        run: |
          set -euo pipefail

          echo "::group::pnpm env & registry"
          pnpm -v
          node -v
          pnpm config list || true
          pnpm config get registry || true
          echo "lockfile sha256: $(sha256sum pnpm-lock.yaml | awk '{print $1}')" || true
          echo "::endgroup::"

          n=0
          until [ $n -ge 3 ]; do
            if pnpm install --frozen-lockfile; then
              OK=1; break
            fi
            n=$((n+1))
            echo "pnpm install --frozen-lockfile failed (attempt $n). Retrying in 10s..."
            sleep 10
          done

          if [ "${OK:-0}" != "1" ]; then
            echo "::warning::Frozen install failed after 3 attempts; checking for outdated lockfile…"
            if grep -E "ERR_PNPM_OUTDATED_LOCKFILE|Lockfile is up to date, but" -i pnpm-debug.log >/dev/null 2>&1; then
              echo "::notice::Detected lockfile drift; attempting non-frozen install (CI fallback)."
              pnpm install --no-frozen-lockfile
            else
              echo "::error::pnpm install failed; see pnpm-debug.log"
              exit 1
            fi
          fi

      - name: Build (workspace)
        run: pnpm -w run build || echo "No build script at root"

      - name: Upload pnpm/build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-logs-build
          path: |
            **/pnpm-debug.log
            pnpm-debug.log
            build-*.log
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload web build (if present)
        if: ${{ hashFiles('apps/web/.next/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: |
            apps/web/.next
            apps/web/next.config.*js
            apps/web/package.json
          if-no-files-found: ignore
          retention-days: 7

  # -----------------------
  # Tests (with Postgres/Redis)
  # -----------------------
  test:
    runs-on: ubuntu-latest
    needs: [build]
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: appdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/appdb
      REDIS_URL: redis://localhost:6379
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Compute pnpm store path
        id: pnpm-store
        run: echo "STORE_PATH=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install deps (frozen)
        run: pnpm install --frozen-lockfile

      - name: Prisma generate (if present)
        run: |
          if [ -f packages/db/prisma/schema.prisma ]; then
            pnpm --filter @bowdoin/db exec prisma generate
          fi

      - name: Run unit tests
        run: |
          if pnpm -w exec vitest --version >/dev/null 2>&1; then
            pnpm -w exec vitest run --coverage --reporter=dot
          elif pnpm -w exec jest --version >/dev/null 2>&1; then
            pnpm -w exec jest --ci --coverage
          else
            echo "No known test runner; skipping tests."
          fi

      - name: Upload coverage (if generated)
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage/**
            **/coverage/**
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload pnpm logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-logs-test
          path: |
            **/pnpm-debug.log
            pnpm-debug.log
          if-no-files-found: ignore
          retention-days: 7
